### ISSUE TITLE
Add more cities

### ISSUE THREAD

**Issue by mycaule** [mycaule/can-we-row#1]
Merci de formuler vos demandes pour ajouter une ville ici

Vous devrez indiquer la nom de la ville avec si possible ses coordonnées GPS et le code de la station Vigicrue.

**Comment by fr25346** [comment]
Bonjour,
Vous serait-il possible d'ajouter Blois (K447001001 - http://www.hydro.eaufrance.fr/stations/K4470010&procedure=fiche-station) ?
En vous remerciant par avance.
F Lhumeau
